- name: configuring catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: enable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: instal nodejs
    ansible.builtin.dnf:
      name: nodejs:20
      state: present
  - name: add system user roboshop
    ansible.builtin.user:
      name: roboshop
      comment: "System User for Automation"
      system: yes
      create_home: /app
      shell: /sbin/nologin
      state: present
  - name: create a folder for app
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download the package
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp

  - name: unarchive the package
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies from package.json
    community.general.npm:
      path: /app
      state: present
  - name: copy catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongo client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present