- name: create ec2 instances and route53 records
  hosts: all
  connection: local
  vars:
    domain_name: sgonly.online
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-0d0209968f87e37ab
    env: dev
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{item}}-{{env}}"
      instance_type: t2.micro
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
      tags:
        Environment: "{{env}}"
        Name: "{{item}}-{{env}}"
    loop: "{{instances}}"
    register: ec2_output

  - name: print ec2 output 
    ansible.builtin.debug:
      msg: "{{ec2_output}}"

